name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  formula:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, ubuntu-24.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@e99025eb970cfa124b8284a35463d87426917478 # 2026.09.28.1

      - name: Set up the Git user
        uses: Homebrew/actions/git-user-config@e99025eb970cfa124b8284a35463d87426917478 # 2026.09.28.1

      - name: Test the formulae
        run: |
          brew test-bot --only-cleanup-before
          brew test-bot --only-tap-syntax
          brew test-bot --only-formulae
